export {
  COMMISSION_INCOME_SUBCATEGORY,
  FIXED_LEASE_EXPENSE_SUBCATEGORY,
  FIXED_MANAGEMENT_FEE_SUBCATEGORY,
  MANAGEMENT_REVENUE_CATEGORY,
  OWNER_LIABILITY_CATEGORY_FILTERS,
  OWNER_PAYMENT_CATEGORY_LEGACY,
  OWNER_PAYOUT_CATEGORY
} from "./finance-categories";

/** Legacy category string on historical expense rows. */
export const OWNER_PAYMENT_CATEGORY = "owner_payment";
